services:
  db:
    image: postgis/postgis:17-master
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  jupyter:
    image: quay.io/jupyter/datascience-notebook
    command: start-notebook.py --NotebookApp.token='${JUPYTER_ACCESS_TOKEN}'
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      postgres_db: ${POSTGRES_DB}
      postgres_user: ${POSTGRES_USER}
      postgres_password: ${POSTGRES_PASSWORD}

  app:
    build: ./app
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    environment:
      postgres_db: ${POSTGRES_DB}
      postgres_user: ${POSTGRES_USER}
      postgres_password: ${POSTGRES_PASSWORD}

volumes:
  postgres_data:
